sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - npm run semantic-release
env:
  global:
    - secure: begvptCFMyfuZq93enjB8rIDtvG5gBiCY0HLlNSVzD3/YzZSo9ctAAO22Kpz7vAGaPF4iRef35I8hz9MQvR+Ppxp9Bo7icrkMAqV+uOFqxfPOc2JiKXqPOHsnZo6ygO2sX+ALWU8e0apkb4r2aFfGkalOLMIgzxENWEgXRPn2oIxtd1MoZnaFrjavbyINXfLhR5BU5sdii6w8rdhHoyqp3dK+dZfj4SSNCNxrXbDLhvvaB2ALrqLh7Sb9LvexwAanx/VfMmij+eK5SgCryKTrtlRYVOjF6sKF7tftg1W20EhFPJoylM5dLC+MrbtOARkUVIJTgUP1Ol8i6RLgiYHfw6nMLzwkg9MpCHnNUMJ+BGroSeAeOgbrRpCFD6BO4pgph+VenqEAPDfhkJb2+BzSFAVO58XJm+9zQvkXIwk2znoUEkWpd6yNkZUjrPQ1/IeoLN9o/HfScFlDbfL6fYPzoA1Q9wqkqYlKbU47+c/emU0yoMyFwanrqSU0cd7+/uu5yHT6sAwvtfdWBo/mDBj3e5ZtwPQibIP5Pk6nAcxs2BHzvjIK7FGY/6M5GdOv5TTfSM8rEcOYk8rvUO9NFPxjqCoiNnEOG0Q/BQMhTNy3wfzDCuAY+JGvzF6OoK3me5giBS9/SEiGstkRUH13Me1FYV+Pj0MiRn/BS8ggxAqCZ8=
    - secure: BFn+V5jeUOpQuYbqPz7BpcMZDw+b9ctpvFBfZhuzeP7Vj7ZACzxNi/MzcaeARG9NPGBMhtNl9wKnpx9CWuwX+TtpyF2J8WDnrAnIj65c62LI9Ycp+tOX+FLmC2GwX7J2KclFATTOhUzXt05PjA1cKcBoPFPcjQktILFt+ohcD4CL9Uj/CSSjAAZbnJgLUTFr57oFap7l7fyFrP6v75HtCTIKcNuJS+vhjdY1VwOq1SIv+vtdrmL2W7op8hH+PyczUAaQkNbb3bnmphoVaq8sVaucjNtQn9C4LddDg/Q3sSkgt2bpb/kOPuZPrylZa2gu6GYfmkpBQXgiHLxf968Eq5ucDS0KxdZor8qP9w+BeHixq3MqIgwyuFG/mdiBxjr9EaRfIX7qHvzbYkq5/oZ3Db+zZJAXeH7W/Sg4XIEjhllD3i/VHS5eDI8BQVIn9oR5NB8QX0noUofboAL8D3O6FniJWd+oGjEFAaf9hoSfLfQ8L3R2DkcUIlGhdMLzY2x85xT/++B0pQQ818aggzU5XyOMiNtZVjjjJqfjw8HwJH6MCXvtXuViDBiRx6aeowleR7pwioeS54k2AzT7Yt2S3iPn55hhDMMtCv2KnWJTcd633T+w736LHZemt8TM0KTnkXziKtS9VfTNftzF8YWOY901x9s2R2cFulgUmOa3cCA=
